spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB53Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #스웨거 설정ㅎ

  datasource:
    url: jdbc:mariadb://rds-anohi-prod.cmjvnjxgjlx4.ap-northeast-2.rds.amazonaws.com/anohi?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: anohihansam
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        type: trace

key:
  jwtSecret: anohironniejamesdiorobhalfoldkarstenjagerdavidvincent

server:
  port: 8080