spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB53Dialect

  datasource:
    url: jdbc:mariadb://localhost:3306/anohi?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        type: info

key:
  jwtSecret: anohironniejamesdiorobhalfoldkarstenjagerdavidvincent