spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB53Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #스웨거 설정ㅎ

  datasource:
    url: jdbc:mariadb://localhost:3306/anohi?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        type: trace

key:
  jwtSecret: anohironniejamesdiorobhalfoldkarstenjagerdavidvincent